apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
data:
  username: cm9vdA==  # Replace with Base64-encoded username for PostgreSQL
  password: cm9vdA==  # Replace with Base64-encoded password for PostgreSQL
